package config

import (
	"Typhoon/utils"
	"fmt"
	"os"
	"path/filepath"
)

const defaultMihomoConfigYAMLTemplate = `
# Default Mihomo configuration template generated by Typhoon
# This file serves as a base. Typhoon will patch this to create a runtime.yaml.

# Basic settings - Typhoon will override these via patching based on its own config.json
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893 # Example, can be set via Typhoon
allow-lan: true
mode: rule # rule / global / direct
log-level: info # debug / info / warning / error / silent
external-controller: '0.0.0.0:9999' # Will be patched by Typhoon
secret: '' # If you want to set a secret for Mihomo's API, do it here or manage via Typhoon if supported

# DNS settings - Typhoon will override these
dns:
  enable: true
  listen: 0.0.0.0:53 # Will be patched
  ipv6: false
  enhanced-mode: redir-host # redir-host / fake-ip
  fake-ip-range: 198.18.0.1/16
  # nameserver:
    # - 114.114.114.114
    # - 8.8.8.8
  # fallback:
    # - tls://1.0.0.1:853
  # fallback-filter:
    # geoip: true
    # geoip-code: CN
    # ipcidr:
      # - 210.140.131.222/32
    # domain:
      # - '+.google.com'
      # - '+.facebook.com'
      # - '+.youtube.com'

# TUN device settings - Typhoon will override if TUN is enabled in Typhoon's config
tun:
  enable: false # Will be patched by Typhoon
  stack: system # system / gvisor / mixed. Will be patched by Typhoon
  # dns-hijack: # Will be patched by Typhoon
    # - any:53
  # auto-route: true
  # auto-detect-interface: true

# Proxy providers (subscriptions) - Users should manage these via subscriptions in Typhoon
# or by manually editing this config.yaml for the profile if not using Typhoon's sub management.
# proxy-providers:
#   mySub:
#     type: http
#     url: "YOUR_SUB_URL_HERE"
#     path: ./providers/mySub.yaml
#     interval: 3600 # Update interval in seconds
#     health-check:
#       enable: true
#       url: http://www.gstatic.com/generate_204
#       interval: 600

# Proxies - Can be populated by proxy-providers or defined manually
# proxies:
#   - name: "Manual Proxy Example"
#     type: ss
#     server: your_server_address
#     port: 8888
#     cipher: aes-256-gcm
#     password: "your_password"

# Proxy Groups - Define how proxies are selected
# proxy-groups:
#   - name: "PROXY"
#     type: select
#     proxies:
#       - mySub # Example if using provider
#       - "Manual Proxy Example"
#       - DIRECT

# Rules - Define how traffic is routed
# rules:
#   - DOMAIN-SUFFIX,google.com,PROXY
#   - DOMAIN-KEYWORD,facebook,PROXY
#   - GEOIP,CN,DIRECT
#   - MATCH,PROXY

# Ensure these directories exist if you use local rule/proxy providers
# rule-providers:
# profile:
#   store-selected: true # Remember the selected proxy in select group
# experimental:
#   sniff-tls-sni: true
`

// EnsureMihomoProfileExists checks if the specified Mihomo profile's config.yaml exists.
// If not, it creates the directory and a default config.yaml from a template.
func EnsureMihomoProfileExists(profileName string) error {
	if profileName == "" {
		return fmt.Errorf("Mihomo profile name cannot be empty")
	}

	execDir, err := utils.GetExecutableDir()
	if err != nil {
		return fmt.Errorf("failed to get executable directory: %w", err)
	}

	profileDir := filepath.Join(execDir, "mihomo", "config", profileName)
	configFilePath := filepath.Join(profileDir, "config.yaml")

	// Check if config file already exists
	if _, err := os.Stat(configFilePath); err == nil {
		// File exists, do nothing
		return nil
	} else if !os.IsNotExist(err) {
		// Error other than file not existing
		return fmt.Errorf("failed to check Mihomo profile config %s: %w", configFilePath, err)
	}

	// File does not exist, create it
	fmt.Printf("Mihomo profile '%s' not found. Creating default config at %s\n", profileName, configFilePath)

	// Create the profile directory
	if err := os.MkdirAll(profileDir, 0755); err != nil {
		return fmt.Errorf("failed to create Mihomo profile directory %s: %w", profileDir, err)
	}

	// Write the default template to config.yaml
	if err := os.WriteFile(configFilePath, []byte(defaultMihomoConfigYAMLTemplate), 0644); err != nil {
		return fmt.Errorf("failed to write default Mihomo config.yaml to %s: %w", configFilePath, err)
	}

	fmt.Printf("Successfully created default Mihomo config for profile '%s'.\n", profileName)
	return nil
}
